### ISSUE TITLE
Long computation time in compute_logprobs function

### ISSUE THREAD

**Issue by zpqiu** [NVIDIA/NeMo-RL#160]
## Problem Description

For a GRPO exp, under the similar settings, Reinforcer takes approximately 550s for this step, while veRL only takes about 120s.

<details>
<summary>Config file</summary>

```yaml
# GRPO Algorithm Configuration
grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 32
  max_num_steps: 1000000
  normalize_rewards: true
  use_leave_one_out_baseline: false
  val_period: 10
  val_at_start: false
  max_val_samples: 128
  val_batch_size: 128

loss_fn:
  reference_policy_kl_penalty: 0
  ratio_eps_min: 0.2
  ratio_eps_max: 0.2

checkpointing:
  enabled: true
  checkpoint_dir: "results/grpo"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 10
  save_period: 10

policy:
  model_name: "Qwen/Qwen2.5-7B"
  tokenizer_name: ${policy.model_name}
  train_global_batch_size: 32
  train_micro_batch_size: 1
  generation_batch_size: 32 # Only used when generating using HF backend
  logprob_batch_size: 2
  max_total_sequence_length: 6144
  precision: "bfloat16"

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 1e-6
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 10
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [10]

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    vllm_cfg:
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.6
      max_model_len: ${policy.max_total_sequence_length}

data:
  max_input_seq_length: 1024 # upper bound, real truncation occurs at vllm.max_model_len
  prompt_file: "examples/r1/cot.txt"
  system_prompt_file: null
  dataset_name: "math-cl"
  
env:
  math:
    num_workers: 8

logger:
  log_dir: "logs"  # Base directory for all logs
  num_val_samples_to_print: 2 # Number of validation samples to pretty print on terminal
  wandb_enabled: true
  tensorboard_enabled: false
  monitor_gpus: false  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "reinforcer_grpo_qwen2_5_7b_cl"
    name: "qwen2_5_7b_grpo_cl"
  tensorboard: {}
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 8
  num_nodes: 1
```
</details>

## Root Cause Analysis

* `input_ids` are padded to the same `seq_len` before `compute_logprobs` is called
* In each micro batch, `input_ids` shape is `[micro_batch_size, max_seq_len (global batch)]`, but the actual `max_seq_len` should vary between micro batches, i.e., there should be different `micro_seq_len` for each micro batch

## Solution

* In the [get_logprobs](https://github.com/NVIDIA/reinforcer/blob/98606cd48deac542c4d0b86fd53f0b3101b0b270/nemo_reinforcer/models/policy/hf_policy.py#L376) function, each micro batch's `input_ids` is trimmed to `[micro_batch_size, max_seq_len (micro batch)]` before being fed into the model for forward computation
* Before returning the results, pad them back to `[micro_batch_size, max_seq_len (global batch)]`

```python
def get_logprobs(self, data: BatchedDataDict) -> BatchedDataDict:
      """Get the logprobs of the model for a batch of data.

      Uses the configured logprob_batch_size to do microbatching.

      Input data is assumed to be right-padded. The method internally converts to
      left-padded format for computation, and returns outputs in right-padded format.

      Returns:
        a BatchedDataDict with key "logprobs" and shape [batch_size, sequence_length].
        We use the convention that the logprob of the first token is 0 so that the sequence length is maintained.
        The logprob of input token i is specified at position i in the output logprobs tensor.
      """
      logprob_batch_size = self.cfg["logprob_batch_size"]
      all_log_probs = []
      self.model.eval()

      # Process in batches
      with torch.no_grad():
          data.to("cuda")
          for lp_batch in data.make_microbatch_iterator(logprob_batch_size):
              input_ids = lp_batch.get("input_ids")
              batch_size, global_batch_seq_len = input_ids.shape

              # Create attention mask
              input_lengths = lp_batch.get("input_lengths")
              max_len_in_microbatch = input_lengths.max().item()

              # Trim input_ids to the max length in the current microbatch
              if max_len_in_microbatch < global_batch_seq_len:
                  input_ids = input_ids[:, :max_len_in_microbatch]

              # Create attention mask for right-padded data
              attention_mask = torch.zeros(
                  (batch_size, max_len_in_microbatch), dtype=torch.long, device=input_ids.device
              )
              for i, length in enumerate(input_lengths):
                  # For right-padded sequence, set 1s at the beginning of the sequence
                  attention_mask[i, :length] = 1

              print("@alex@", input_ids.shape)

              # Process with the model directly using right-padded inputs
              with torch.autocast(device_type="cuda", dtype=self.dtype):
                  outputs = self.model(
                      input_ids=input_ids,
                      attention_mask=attention_mask,
                      use_cache=False,
                  )
              log_probs = torch.nn.functional.log_softmax(
                  outputs.logits.to(torch.float32), dim=-1
              )

              # Extract logprobs for each token in the sequence by gathering the logprob
              # corresponding to the next token at each position
              # Input shapes:
              #   log_probs: [batch_size, sequence_length, vocab_size] - logits for each position
              #   token_ids: [batch_size, sequence_length] - actual tokens
              # Output shape: [batch_size, sequence_length] - logprob of each token given previous
              # We get logprob of token[t+1] from logits[t], prepending 0 to maintain sequence length
              token_ids = input_ids
              next_tokens = token_ids[:, 1:]  # Skip first token
              log_probs = log_probs[:, :-1]  # Remove last position's logits
              token_logprobs = log_probs.gather(
                  dim=-1, index=next_tokens.unsqueeze(-1)
              ).squeeze(-1)

              # Prepend 0 logprob for first token to maintain same sequence length as input
              token_logprobs = torch.cat(
                  [torch.zeros_like(token_logprobs[:, :1]), token_logprobs], dim=1
              )

              # Apply mask to zero out padding tokens logprobs
              token_logprobs = token_logprobs * attention_mask
              
              # Restore to the original sequence length (pad with zeros)
              if max_len_in_microbatch < global_batch_seq_len:
                  padded_logprobs = torch.zeros(
                      (batch_size, global_batch_seq_len), 
                      dtype=token_logprobs.dtype, 
                      device=token_logprobs.device
                  )
                  padded_logprobs[:, :max_len_in_microbatch] = token_logprobs
                  token_logprobs = padded_logprobs
              
              all_log_probs.append(token_logprobs)

      # Concatenate all batches
      return_data = BatchedDataDict()
      return_data["logprobs"] = torch.cat(all_log_probs, dim=0).cpu()

      return return_data
```

## Results

After dynamically trimming, with the same settings, `compute_logprobs` execution time decreased from 550s to 370s (reduced by over **30%**). There's still room for optimization as detailed below.

## Additional Optimization Opportunities

* Reduce the cost of trimming operations themselves
* Currently, data is sharded to different workers sequentially, but it should be distributed based on `seq_length` to achieve better load balancing and avoid workload imbalance between workers.
* The `train` function may have the same issue

cc @sharonyu-115 @terrykong
